# Generated by Django 2.2 on 2019-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190429_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점')], default='', max_length=1),
        ),
    ]
